#![allow(
    clippy::write_with_newline,
    clippy::new_without_default,
    rustdoc::private_intra_doc_links
)]

use lalrpop_util::lalrpop_mod;

pub mod ast;
pub mod bc;
pub mod rt;
pub mod stdlib;
pub mod tir;
pub mod utils;

lalrpop_mod!(
    #[allow(clippy::all)]
    /// Parser generated by LALRPOP.
    pub grammar,
    "/ast/grammar.rs"
);

pub use ast::{parse, read};
pub use bc::{analyze, lower, optimize};
pub use tir::typecheck;
